# Generated by Django 6.0 on 2025-12-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, help_text='List of key features', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Lucide icon name e.g. Megaphone', max_length=50),
        ),
    ]
