# Generated by Django 6.0 on 2025-12-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_features_service_img_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='List of key features', null=True),
        ),
    ]
