# Generated by Django 6.0 on 2025-12-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Hero Section'), ('banner', 'Banner'), ('scrollbar', 'Scrollbar'), ('service', 'Service'), ('why_choose', 'Why Choose'), ('our_team', 'Our Team'), ('clients_showcase', 'Clients Showcase'), ('partners', 'Partners'), ('contact', 'Contact Section'), ('blog', 'Blog Section')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
