# Generated by Django 6.0 on 2025-12-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectpost_projectpostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
