# Generated by Django 6.0 on 2025-12-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectpost_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='img',
        ),
        migrations.AddField(
            model_name='projectpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
