# Generated by Django 6.0 on 2025-12-31 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_projectpost_img_projectpost_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpost',
            options={},
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='projectpostimage',
            name='image',
            field=models.ImageField(upload_to='project_posts/'),
        ),
        migrations.CreateModel(
            name='ServiceTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.service')),
            ],
        ),
    ]
