# Generated by Django 6.0 on 2026-01-01 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projectpost_options_alter_projectpost_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/banners/'),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/features/'),
        ),
        migrations.AddField(
            model_name='projectpostimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectpostimage',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='projectpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.projectpost'),
        ),
    ]
