# Generated by Django 6.0 on 2026-01-01 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_projectpost_banner_img_projectpost_feature_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpostimage',
            name='post',
        ),
        migrations.AddField(
            model_name='projectpostimage',
            name='project_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.projectpost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectpostimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectpostimage',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
