# Generated by Django 6.0 on 2026-01-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_alter_projectpostimage_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
    ]
