# Generated by Django 6.0 on 2026-01-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_post_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
