# Generated by Django 6.0 on 2026-01-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetimeline',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='servicetimeline',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
