# Generated by Django 6.0 on 2025-12-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_herosection_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(max_length=50),
        ),
    ]
