# Generated by Django 6.0 on 2025-12-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bannerstat_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=list)),
                ('growth_projects', models.CharField(default='500+', max_length=50)),
                ('senior_experts', models.CharField(default='50+', max_length=50)),
                ('mena_mastery', models.CharField(default='10y+', max_length=50)),
                ('client_satisfaction_rate', models.CharField(default='98%', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
            ],
        ),
    ]
