# Generated by Django 6.0 on 2025-12-25 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='client_satisfaction_rate',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='growth_projects',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='mena_mastery',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='senior_experts',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='img_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='img_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='home.aboutsection')),
            ],
        ),
    ]
