# Generated by Django 6.0 on 2025-12-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_feature_whychooseus_whychooseuspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
