# Generated by Django 6.0 on 2025-12-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testimonial_testimonialsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonialsection',
            options={},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_id',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonialsection',
            name='title_1',
            field=models.CharField(max_length=255),
        ),
    ]
