# Generated by Django 6.0 on 2026-01-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_testimonial_image_url_testimonial_image'),
    ]

    operations = [
    ]
