# Generated by Django 6.0 on 2026-01-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('ae', 'UAE')], default='global', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='bannerstat',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('ae', 'UAE')], default='global', max_length=10),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('ae', 'UAE')], default='global', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('ae', 'UAE')], default='global', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='testimonialsection',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('ae', 'UAE')], default='global', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('ae', 'UAE')], default='global', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(help_text='Icon name (e.g., BarChart3)', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(max_length=100),
        ),
    ]
